### ISSUE TITLE
question // any reason to use CMake released 4 years ago?

### ISSUE THREAD

**Issue by snikulov** [PacktPublishing/Embedded-Programming-with-CPP-Cookbook#1]
Hello, @iverg 

Are any particular reasons to use so old CMake (CMake 3.5.1 March 24, 2016)?

I see the following code 
```
cmake_minimum_required(VERSION 3.5.1)
...
SET(CMAKE_CXX_FLAGS "--std=c++11")
```
and have no viable explanation of why I should buy your book in 2020.

The only reason which comes into my mind, we sometimes use aged Enterprise Linux (RHEL 7) for embedded development, but it provides CMake version cmake3-3.17.2-1.el7.src.rpm

For Ubuntu LTE situation is even better - Kitware provides apt repository https://apt.kitware.com/

**Comment by iverg** [comment]
Hi Sergey,

This is a minimum version. CMake rules in the examples are very simple and
can work with pretty outdated versions of make. It does not limit you
however to use this version.\

Best,
Igor

**Comment by snikulov** [comment]
Thank you for your explanation.
